package cakeexample.framework.gnurf;

import cakeexample.framework.domain.AbstractField;
import fj.data.List;

import java.sql.ResultSet;
import java.util.Optional;

public class Expression<C> {
    private final DbUtil dbUtil;
    private final Table<C> table;

    public Expression(DbUtil dbUtil, Table<C> table) {
        this.dbUtil = dbUtil;
        this.table = table;
    }

    public List<C> selectAll() {
        return dbUtil.select(table.name, (ResultSet r) -> table.entityConstructor.apply(table.columns.map(c -> harmoniseGenerics(r, c))));
    }

    private <V> AbstractField<C, V> harmoniseGenerics(ResultSet r, AbstractColumn<C, V> c) {
        return dbUtil.columnMapper(c).f(r, c);
    }

    public C update(C c) {
        throw new RuntimeException("Not implemented");
    }

    public InsertContinuation insert(C entity) {
        return new InsertContinuation(dbUtil.insert(table.name, table.columns.map(c -> harmoniseTypes(c, entity))));
    }

    private static <C, V> AbstractColumn<C, V> harmoniseTypes(AbstractColumn<C, V> c, C entity) {
        return c.withField(c.field().as(c.field().getter().get().f(entity)));
    }

    public class InsertContinuation {
        public final Optional<Long> autogeneratedKey;

        public InsertContinuation(Optional<Long> autogeneratedKey) {
            this.autogeneratedKey = autogeneratedKey;
        }

        public C retrieve() {
            throw new RuntimeException("Not implemented");
        }

        public <V extends Number> Optional<V> id() {
            return dbUtil.getLastGeneratedValue();
        }
    }

}
