package cakeexample.framework.gnurf;

import fj.data.List;

import java.util.Optional;

public class Expression<C> {
    private final DbUtil dbUtil;
    private final Table<C> table;

    public Expression(DbUtil dbUtil, Table<C> table) {
        this.dbUtil = dbUtil;
        this.table = table;
    }

    public List<C> selectAll() {
        return dbUtil.select(table.name, r -> table.entityConstructor.apply(table.columns.map(c -> c.withResult(r))));
    }

    public C update(C c) {
        throw new NotImplementedException();
    }

    public InsertContinuation insert(C entity) {
        return new InsertContinuation(dbUtil.insert(table.name, table.columns.map(c -> addEntityValue(c, entity))));
    }

    private static <C, V> AbstractColumn<C, ?> addEntityValue(AbstractColumn<C, V> c, C entity) {
        // TODO more information in error (which table for example or get position from stack trace during creation)
        //noinspection unchecked
        return c.columnValue(entity)
                .map(value -> c.withField(c.field().as((V) value)))
                .orElseThrow(() -> new RuntimeException("Field of column " + c.name() + " missing getter function"));
    }

    public class InsertContinuation {
        public final Optional<Long> autogeneratedKey;

        public InsertContinuation(Optional<Long> autogeneratedKey) {
            this.autogeneratedKey = autogeneratedKey;
        }

        public C retrieve() {
            throw new RuntimeException("Not implemented");
        }

        public <V extends Number> Optional<V> id() {
            return dbUtil.getLastGeneratedValue();
        }
    }

}
